export interface Env { DB: D1Database; UPLOADS: R2Bucket; CONFIG: KVNamespace; OPENAI_API_KEY: string }
const CORS = {'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'};
function json(data:any,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json',...CORS}})}
function id(p='id'){return `${p}_${crypto.randomUUID()}`}
async function openai(env:Env, body:any){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'authorization':`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)}); if(!r.ok) throw new Error(await r.text()); return r.json()}
const analysisSchema = {type:'object',additionalProperties:false,properties:{summary:{type:'string'},quality_score:{type:'integer'},escalation_score:{type:'integer'},validation_score:{type:'integer'},collaboration_score:{type:'integer'},topic_drift_score:{type:'integer'},resolution_probability:{type:'integer'},outcome:{type:'string',enum:['resolved','escalated','unresolved','deferred']},messages:{type:'array',items:{type:'object',additionalProperties:false,properties:{speaker:{type:'string'},body:{type:'string'},idx:{type:'integer'}},required:['speaker','body','idx']}},topics:{type:'array',items:{type:'string'}},themes:{type:'array',items:{type:'string'}},horsemen:{type:'object',additionalProperties:false,properties:{relationship:{type:'object',additionalProperties:false,properties:{criticism:{type:'integer'},defensiveness:{type:'integer'},contempt:{type:'integer'},stonewalling:{type:'integer'}},required:['criticism','defensiveness','contempt','stonewalling']},speakers:{type:'object',additionalProperties:{type:'object',additionalProperties:false,properties:{criticism:{type:'integer'},defensiveness:{type:'integer'},contempt:{type:'integer'},stonewalling:{type:'integer'}},required:['criticism','defensiveness','contempt','stonewalling']}},evidence:{type:'array',items:{type:'object',additionalProperties:true}}},required:['relationship','speakers','evidence']},repair:{type:'object',additionalProperties:false,properties:{relationship:{type:'object',additionalProperties:false,properties:{validation:{type:'integer'},accountability:{type:'integer'},appreciation:{type:'integer'},compromise:{type:'integer'},reconnection:{type:'integer'},successful_repairs:{type:'integer'},failed_repairs:{type:'integer'}},required:['validation','accountability','appreciation','compromise','reconnection','successful_repairs','failed_repairs']},speakers:{type:'object',additionalProperties:{type:'object',additionalProperties:false,properties:{validation:{type:'integer'},accountability:{type:'integer'},appreciation:{type:'integer'},compromise:{type:'integer'},reconnection:{type:'integer'},successful_repairs:{type:'integer'},failed_repairs:{type:'integer'}},required:['validation','accountability','appreciation','compromise','reconnection','successful_repairs','failed_repairs']}},evidence:{type:'array',items:{type:'object',additionalProperties:true}}},required:['relationship','speakers','evidence']},loops:{type:'array',items:{type:'string'}},unanswered_questions:{type:'array',items:{type:'string'}},coaching:{type:'array',items:{type:'string'}}},required:['summary','quality_score','escalation_score','validation_score','collaboration_score','topic_drift_score','resolution_probability','outcome','messages','topics','themes','horsemen','repair','loops','unanswered_questions','coaching']};
async function analyze(env:Env, input:{title:string, raw_text:string, source_type:string}){
 const convId=id('conv');
 const prompt = `Analyze this relationship communication. Do not decide who is right. Identify communication patterns, topics, themes, conflict outcome, Four Horsemen, repair attempts, topic drift, loop patterns, unanswered questions, and coaching suggestions. Score 0-100. Normalize pasted conversation into messages.\n\nConversation:\n${input.raw_text}`;
 const result = await openai(env,{model:'gpt-5.5',input:[{role:'system',content:'You are Project Black Box, a neutral communication intelligence engine. Avoid diagnosis, legal conclusions, and moral rulings.'},{role:'user',content:prompt}],text:{format:{type:'json_schema',name:'blackbox_analysis',schema:analysisSchema,strict:true}}});
 const text = result.output_text ?? result.output?.flatMap((o:any)=>o.content||[]).map((c:any)=>c.text).join('\n');
 const a = JSON.parse(text); a.conversation_id=convId;
 await env.DB.prepare('INSERT INTO conversations (id,user_id,title,source_type,raw_text,outcome,quality_score,escalation_score,validation_score,collaboration_score,topic_drift_score,resolution_probability) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)')
  .bind(convId,'local',input.title||'Conversation',input.source_type,input.raw_text,a.outcome,a.quality_score,a.escalation_score,a.validation_score,a.collaboration_score,a.topic_drift_score,a.resolution_probability).run();
 for(const m of a.messages) await env.DB.prepare('INSERT INTO messages (id,conversation_id,speaker,body,idx) VALUES (?,?,?,?,?)').bind(id('msg'),convId,m.speaker,m.body,m.idx).run();
 for(const t of a.topics) await env.DB.prepare('INSERT INTO topics (id,conversation_id,topic,confidence) VALUES (?,?,?,?)').bind(id('topic'),convId,t,1).run();
 for(const t of a.themes) await env.DB.prepare('INSERT INTO themes (id,conversation_id,theme,confidence) VALUES (?,?,?,?)').bind(id('theme'),convId,t,1).run();
 await env.DB.prepare('INSERT INTO analysis_runs (id,conversation_id,model,json) VALUES (?,?,?,?)').bind(id('run'),convId,'gpt-5.5',JSON.stringify(a)).run();
 for(const [speaker,score] of Object.entries(a.horsemen.speakers)) await env.DB.prepare('INSERT INTO horsemen_scores (id,conversation_id,speaker,criticism,defensiveness,contempt,stonewalling,evidence_json) VALUES (?,?,?,?,?,?,?,?)').bind(id('horse'),convId,speaker,(score as any).criticism,(score as any).defensiveness,(score as any).contempt,(score as any).stonewalling,JSON.stringify(a.horsemen.evidence)).run();
 for(const [speaker,score] of Object.entries(a.repair.speakers)) await env.DB.prepare('INSERT INTO repair_scores (id,conversation_id,speaker,validation,accountability,appreciation,compromise,reconnection,successful_repairs,failed_repairs,evidence_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id('repair'),convId,speaker,(score as any).validation,(score as any).accountability,(score as any).appreciation,(score as any).compromise,(score as any).reconnection,(score as any).successful_repairs,(score as any).failed_repairs,JSON.stringify(a.repair.evidence)).run();
 await env.DB.prepare('INSERT INTO conflict_outcomes (id,conversation_id,outcome,rationale) VALUES (?,?,?,?)').bind(id('outcome'),convId,a.outcome,a.summary).run();
 return a;
}
async function coach(env:Env,draft:string){
 const schema={type:'object',additionalProperties:false,properties:{risk:{type:'string'},risk_score:{type:'integer'},risk_drivers:{type:'array',items:{type:'string'}},what_they_may_hear:{type:'array',items:{type:'string'}},what_to_avoid:{type:'array',items:{type:'string'}},suggested_move:{type:'string'},rewrite:{type:'string'}},required:['risk','risk_score','risk_drivers','what_they_may_hear','what_to_avoid','suggested_move','rewrite']};
 const res=await openai(env,{model:'gpt-5.5',input:[{role:'system',content:'You are Coach Mode for Project Black Box. Review drafts neutrally. Recommend safer, clearer, less escalating communication.'},{role:'user',content:draft}],text:{format:{type:'json_schema',name:'coach_report',schema,strict:true}}});
 const text=res.output_text ?? res.output?.flatMap((o:any)=>o.content||[]).map((c:any)=>c.text).join('\n');
 const report=JSON.parse(text); await env.DB.prepare('INSERT INTO coaching_reports (id,user_id,draft,json) VALUES (?,?,?,?)').bind(id('coach'),'local',draft,JSON.stringify(report)).run(); return report;
}
export default { async fetch(req:Request, env:Env){ if(req.method==='OPTIONS') return new Response(null,{headers:CORS}); const url=new URL(req.url); try{
 if(url.pathname==='/api/analyze'&&req.method==='POST') return json(await analyze(env,await req.json() as any));
 if(url.pathname==='/api/coach'&&req.method==='POST'){const b:any=await req.json(); return json(await coach(env,b.draft||''));}
 if(url.pathname==='/api/conversations'&&req.method==='GET'){const q=url.searchParams.get('q'); let sql=`SELECT c.id,c.title,c.created_at,c.outcome,c.quality_score,group_concat(DISTINCT t.topic) topics,group_concat(DISTINCT th.theme) themes FROM conversations c LEFT JOIN topics t ON t.conversation_id=c.id LEFT JOIN themes th ON th.conversation_id=c.id`; const params:any[]=[]; if(q){sql+=` WHERE c.raw_text LIKE ? OR c.title LIKE ? OR t.topic LIKE ? OR th.theme LIKE ?`; params.push(`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`)} sql+=` GROUP BY c.id ORDER BY c.created_at DESC LIMIT 50`; const st=env.DB.prepare(sql).bind(...params); return json((await st.all()).results);}
 if(url.pathname==='/api/upload'&&req.method==='POST'){const form=await req.formData(); const file=form.get('file') as File; if(!file) return json({error:'file required'},400); const key=`uploads/${crypto.randomUUID()}-${file.name}`; await env.UPLOADS.put(key, await file.arrayBuffer(), {httpMetadata:{contentType:file.type}}); const fid=id('file'); await env.DB.prepare('INSERT INTO files (id,user_id,filename,content_type,r2_key) VALUES (?,?,?,?,?)').bind(fid,'local',file.name,file.type,key).run(); let note='File stored in R2. For screenshots/documents, use the Analyze flow after extracting text or add model file processing.'; return json({file_id:fid,r2_key:key,filename:file.name,content_type:file.type,note});}
 return json({ok:true,name:'Project Black Box API',routes:['/api/analyze','/api/coach','/api/conversations','/api/upload']});
 }catch(e:any){return json({error:e.message||String(e)},500)} } }
